### ISSUE TITLE
Docker Container Failing To Compile my Network Based Apps

### ISSUE THREAD

**Issue by Based-Skid** [mlafeldt/docker-ps2dev#1]
Your Docker Container is Failing to Compile my PS2 Homebrew Apps.

I setup Travis with your Docker Container and it is Failing With the Following Apps.

I tested them just to be sure andThey Compile Fine on my Raspberry PI setup with the SDK.

https://github.com/Based-Skid/iLaunchELF

https://github.com/Based-Skid/Ps2-Remote-ASM

**Comment by mlafeldt** [comment]
Probably because the latest version of the image was 9 months old. I rebuilt it. Try the `latest` image tag again.

**Comment by Based-Skid** [comment]
I ended up Setting up my Own Docker Container For this..

https://github.com/Based-Skid/DOCKER-PS2DEV-CI/blob/master/Dockerfile

ps2packer doesnt compile for some reason so i had to exclude it.
